src/Entity/Covoiturage.php
<?php

namespace App\Entity;

use App\Repository\CovoiturageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CovoiturageRepository::class)]
class Covoiturage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_depart = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $heure_depart = null;

    #[ORM\Column(length: 50)]
    private ?string $lieu_depart = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_arrivee = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $heure_arrivee = null;

    #[ORM\Column(length: 50)]
    private ?string $lieu_arrivee = null;

    #[ORM\Column(length: 50)]
    private ?string $statut = null;

    #[ORM\Column]
    private ?int $nb_place = null;

    #[ORM\Column]
    private ?float $prix_personne = null;

    /** @var Collection<int, User> */
    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'covoiturage')]
    private Collection $users;

    #[ORM\ManyToOne(inversedBy: 'covoituragesCrees')]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $conducteur = null;

    #[ORM\ManyToOne(inversedBy: 'covoiturages')]
    private ?Voiture $voiture = null;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTimeInterface $date_depart): static
    {
        $this->date_depart = $date_depart;
        return $this;
    }

    public function getHeureDepart(): ?\DateTimeInterface
    {
        return $this->heure_depart;
    }

    public function setHeureDepart(\DateTimeInterface $heure_depart): static
    {
        $this->heure_depart = $heure_depart;
        return $this;
    }

    public function getLieuDepart(): ?string
    {
        return $this->lieu_depart;
    }

    public function setLieuDepart(string $lieu_depart): static
    {
        $this->lieu_depart = $lieu_depart;
        return $this;
    }

    public function getDateArrivee(): ?\DateTimeInterface
    {
        return $this->date_arrivee;
    }

    public function setDateArrivee(\DateTimeInterface $date_arrivee): static
    {
        $this->date_arrivee = $date_arrivee;
        return $this;
    }

    public function getHeureArrivee(): ?\DateTimeInterface
    {
        return $this->heure_arrivee;
    }

    public function setHeureArrivee(\DateTimeInterface $heure_arrivee): static
    {
        $this->heure_arrivee = $heure_arrivee;
        return $this;
    }

    public function getLieuArrivee(): ?string
    {
        return $this->lieu_arrivee;
    }

    public function setLieuArrivee(string $lieu_arrivee): static
    {
        $this->lieu_arrivee = $lieu_arrivee;
        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): static
    {
        $this->statut = $statut;
        return $this;
    }

    public function getNbPlace(): ?int
    {
        return $this->nb_place;
    }

    public function setNbPlace(int $nb_place): static
    {
        $this->nb_place = $nb_place;
        return $this;
    }

    public function getPrixPersonne(): ?float
    {
        return $this->prix_personne;
    }

    public function setPrixPersonne(float $prix_personne): static
    {
        $this->prix_personne = $prix_personne;
        return $this;
    }

    /** @return Collection<int, User> */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addCovoiturage($this);
        }
        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            $user->removeCovoiturage($this);
        }
        return $this;
    }

    public function getConducteur(): ?User
    {
        return $this->conducteur;
    }

    public function setConducteur(?User $conducteur): static
    {
        $this->conducteur = $conducteur;
        return $this;
    }

    public function getVoiture(): ?Voiture
    {
        return $this->voiture;
    }

    public function setVoiture(?Voiture $voiture): static
    {
        $this->voiture = $voiture;
        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = ['ROLE_USER'];

    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 50)]
    private ?string $telephone = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(type: 'date')]
    private ?\DateTimeInterface $date_naissance = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    #[ORM\Column(length: 50)]
    private ?string $pseudo = null;

    /** @var Collection<int, Avis> */
    #[ORM\ManyToMany(targetEntity: Avis::class, inversedBy: 'users')]
    private Collection $avis;

    /** @var Collection<int, Covoiturage> */
    #[ORM\ManyToMany(targetEntity: Covoiturage::class, inversedBy: 'users')]
    private Collection $covoiturage;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Voiture $voiture = null;

    #[ORM\Column(type: 'string', length: 20)]
    private ?string $type_utilisateur = 'passager'; // valeur par défaut


    public function __construct()
    {
        $this->avis = new ArrayCollection();
        $this->covoiturage = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;
        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;
        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;
        return $this;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';
        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;
        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;
        return $this;
    }

    public function eraseCredentials(): void
    {
        // nothing needed
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;
        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): static
    {
        $this->adresse = $adresse;
        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): static
    {
        $this->date_naissance = $date_naissance;
        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): static
    {
        $this->photo = $photo;
        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;
        return $this;
    }

    /** @return Collection<int, Avis> */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvis(Avis $avis): static
    {
        if (!$this->avis->contains($avis)) {
            $this->avis->add($avis);
            $avis->addUser($this);
        }

        return $this;
    }

    public function removeAvis(Avis $avis): static
    {
        if ($this->avis->removeElement($avis)) {
            $avis->removeUser($this);
        }

        return $this;
    }

    /** @return Collection<int, Covoiturage> */
    public function getCovoiturage(): Collection
    {
        return $this->covoiturage;
    }

    public function addCovoiturage(Covoiturage $c): static
    {
        if (!$this->covoiturage->contains($c)) {
            $this->covoiturage->add($c);
            $c->addUser($this);
        }

        return $this;
    }

    public function removeCovoiturage(Covoiturage $c): static
    {
        if ($this->covoiturage->removeElement($c)) {
            $c->removeUser($this);
        }

        return $this;
    }

    public function getVoiture(): ?Voiture
    {
        return $this->voiture;
    }

    public function setVoiture(?Voiture $voiture): static
    {
        $this->voiture = $voiture;
        return $this;
    }

    public function __toString(): string
    {
        return $this->pseudo ?? $this->email ?? 'Utilisateur';
    }

    public function getTypeUtilisateur(): ?string
{
    return $this->type_utilisateur;
}

    public function setTypeUtilisateur(string $type): self
    {
        $this->type_utilisateur = $type;
        return $this;
    }

}

templates/pages/admin.html.twig
{% extends 'base.html.twig' %}

{% block title %}Administration – Ecoride{% endblock %}

{% block body %}
<main class="container my-5">

    <h2 class="text-center mb-4">Administration</h2>

    <div class="p-4 bg-light rounded shadow-sm">
        <p>
            Bienvenue sur la page d'administration.  
            Utilisez le menu pour accéder aux différentes sections de gestion.
        </p>
        <a href="{{ path('app_logout') }}">Se déconnecter</a>

    </div>

</main>
{% endblock %}

templates/pages/connexion.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {% if app.user %}
        <div class="mb-3">
            You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}

    <form class="connexion-form" method="post">
        
        <h2 class="h3 mb-3 font-weight-normal">Veuillez vous connecter</h2>
        <form action="{{ path('app_connexion') }}" method="post">
        <label for="email">Email:</label>
        <input type="email" name="email" value="{{ last_username }}" required style="border: 2px solid #198754; border-radius: 5px;"><br>
        <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
        <label for="password">Mot de passe:</label>
        <input type="password" name="password" required style="border: 2px solid #198754; border-radius: 5px;"><br>

        <button type="submit" style="background-color: burlywood; color: #198754; border-color: #198754; border-radius: 10px;">Se connecter</button>
        </form>
        
            <div class="checkbox mb-3">
                <input type="checkbox" name="_remember_me" id="_remember_me">
                <label for="_remember_me">Se souvenir de moi</label>
            </div>
    </form>

    <h2 class="not-yet-title">Pas encore de compte ?</h2>

    <a href="{{ path('app_create_user') }}" class="create-account-link">Créer un compte</a>
{% endblock %}

templates/pages/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ecoride{% endblock %}
{% block body %}
    <main>
        <h2 class="contact-title">Contactez-nous</h2>
        <div class="contact-info">
            <p>Pour toute question ou demande d'information, n'hésitez pas à nous contacter à l'adresse suivante :</p>
            <p>Email : <a href="mailto:valle_thomas@hotmail.fr">valle_thomas@hotmail.fr</a></p>
        </div>
    </main>
{% endblock %}

templates/pages/covoiturages.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h2 class="covoiturages-title">Accès aux covoiturages</h2>

<div>
    <p class="covoiturages-description">
        Bienvenue sur la page des covoiturages. Ici, vous pouvez rechercher et réserver des trajets partagés avec d'autres utilisateurs.
    </p>
</div>

{% if covoiturages|length %}
    <div class="d-flex flex-wrap justify-content-center">
        {% for covoiturage in covoiturages %}
            <div class="card-list">
                <div class="card">
                    <div class="card-header">
                        Départ : {{ covoiturage.lieuDepart }} <br>
                        Arrivée : {{ covoiturage.lieuArrivee }}
                    </div>

                    <div class="card-body">

                        <h5 class="card-title">Date : {{ covoiturage.dateDepart|date('d/m/Y') }}</h5>
                        <h5 class="card-title">Heure de départ : {{ covoiturage.heureDepart|date('H:i') }}</h5>
                        <h5 class="card-title">Arrivée estimée : {{ covoiturage.heureArrivee|date('H:i') }}</h5>

                        <p class="card-text">Places disponibles : {{ covoiturage.nbPlace }}</p>
                        <p class="card-text">Prix : {{ covoiturage.prixPersonne }} €</p>

                        <hr>

                        <p class="card-text">
                            👤 Conducteur :
                            {{ covoiturage.conducteur.prenom }} {{ covoiturage.conducteur.nom }}
                        </p>

                        <p class="card-text">
                            🚗 Véhicule :
                            {% if covoiturage.voiture %}
                                {{ covoiturage.voiture.marque }} {{ covoiturage.voiture.modele }}
                            {% else %}
                                <em>Aucune voiture associée</em>
                            {% endif %}
                        </p>

                        <hr>

                        <p class="card-text fw-bold">⭐ Avis sur le conducteur :</p>

                        {% set avisConducteur = covoiturage.conducteur.avis %}
                        
                        {% if avisConducteur|length > 0 %}

                            {% set total = 0 %}
                            {% for avis in avisConducteur %}
                                {% set total = total + avis.note %}
                            {% endfor %}
                            {% set moyenne = (total / avisConducteur|length)|number_format(1) %}

                            <p class="card-text">
                                Note moyenne : <strong>{{ moyenne }}/5</strong> ⭐
                            </p>

                            <ul>
                                {% for avis in avisConducteur %}
                                    <li>
                                        <strong>{{ avis.note }}/5</strong> — {{ avis.commentaire ?: "Pas de commentaire" }}
                                    </li>
                                {% endfor %}
                            </ul>

                        {% else %}
                            <p><em>Aucun avis pour ce conducteur pour le moment.</em></p>
                        {% endif %}

                        <a href="#"
                            class="btn-eco btn-primary"
                            style="background-color: burlywood; color: #198754; border-color: #198754;">
                            Réserver ce covoiturage
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <p class="text-center mt-4">Aucun covoiturage disponible pour le moment.</p>
{% endif %}

<div class="text-center mt-5">
    <a href="{{ path('app_saisir_covoiturage') }}"
        class="button-saisie-voyage"
        style="color: #198754; border-color: #198754;">
        Saisir un covoiturage
    </a>
</div>

{% endblock %}

templates/pages/create.html.twig
{% extends 'base.html.twig' %}

{%block body %}

    <h2 class="create-title">Créer votre profil</h2>

    <div class="form-container">
        {{ form_start(form) }}
            {{ form(form) }}
        {{ form_end(form) }}
    </div>

    <h3 class="create-title">Choisissez votre type de profil</h3>
    <div class="choose-type-container">
        <a href="{{ path('app_change_type_utilisateur', {type: 'conducteur'}) }}"
            class="btn btn-primary">Je suis conducteur</a>

        <a href="{{ path('app_change_type_utilisateur', {type: 'passager'}) }}"
            class="btn btn-secondary">Je suis passager</a>

        <a href="{{ path('app_change_type_utilisateur', {type: 'les_deux'}) }}"
            class="btn btn-success">Je suis les deux</a>
    </div>


{% endblock %}  

templates/pages/employee.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ecoride{% endblock %}

{% block body %}
<body>
    <main>
            <h2>Bienvenue sur votre espace employé</h2>
            <div>
                <p>Gérez les covoiturages, les utilisateurs et les réservations ici.</p>
            </div>
            <a href="{{ path('app_logout') }}">Se déconnecter</a>
    </main>

</body>
{% endblock %} 

templates/pages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ecoride{% endblock %}

{% block body %}

<main class="presentation">
    <h2 class="titre_presentation">Ecoride, qu'est ce que c'est ? Une solution simple et engagée pour réduire les couts à la fois pour votre porte-monnaie et pour la planète !
    </h2>
    <div class="texte_presentation">
        Ecoride est une plateforme de covoiturage qui met en relation des conducteurs et des passagers souhaitant partager un trajet en voiture. Notre mission est de promouvoir une mobilité plus durable en réduisant le nombre de véhicules sur les routes, ce qui contribue à diminuer les émissions de gaz à effet de serre et la congestion urbaine.
    </div>
    <!-- Card présentant les avantages du covoiturage avec Ecoride -->
            <div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
        <div class="card h-100">
        <img src="{{ asset ('Images/route.jpg') }}" class="card-img-top" alt="route">
        <div class="card-body">
            <h5 class="card-title">Ecologie</h5>
            <p class="card-text">Covoiturer est devenu un geste écologique essentiel pour préserver notre planète. Grâce à EcoRide, vous contribuez à réduire votre empreinte carbone en partageant vos trajets avec d'autres passagers. C'est pourquoi nous encourageons le covoiturage responsable et respectueux de l'environnement.</p>
        </div>
        </div>
    </div>
    <div class="col">
        <div class="card h-100">
        <img src="{{ asset ('Images/convivialite.jpg') }}" class="card-img-top" alt="convivialite">
        <div class="card-body">
            <h5 class="card-title">Convivialite</h5>
            <p class="card-text">Le covoiturage favorise les échanges et les rencontres entre les passagers, créant ainsi un esprit de communauté et de convivialité. Avec EcoRide, vous pouvez partager des moments agréables tout en réduisant votre impact environnemental.</p>
        </div>
        </div>
    </div>
    <div class="col">
        <div class="card h-100">
        <img src="{{ asset ('Images/volant.jpg') }}" class="card-img-top" alt="volant">
        <div class="card-body">
            <h5 class="card-title">Economies</h5>
            <p class="card-text">Le covoiturage permet de partager les frais de déplacement, ce qui se traduit par des économies significatives pour les conducteurs et les passagers. Avec EcoRide, vous pouvez réduire vos dépenses liées aux trajets tout en contribuant à un mode de transport plus durable.</p>
        </div>
        </div>
    </div>
    </div>
</main>

{% endblock %}

templates/pages/mentionsLegales.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mentions légales – Ecoride{% endblock %}

{% block body %}
<main class="container my-5 mentions-legales">

    <h2 class="mb-4 text-center">Mentions Légales</h2>

    <section class="mb-4">
        <h4>Éditeur du site</h4>
        <p>EcoRide</p>

        <h4>Responsable de la publication</h4>
        <p>Thomas Valle</p>

        <h4>Hébergeur</h4>
        <p>[Nom de l'hébergeur]</p>
    </section>

    <section class="mb-4">
        <h4>Propriété intellectuelle</h4>
        <p>
            Tous les contenus présents sur ce site sont protégés par le droit d'auteur.  
            Toute reproduction ou distribution sans autorisation est interdite.
        </p>
    </section>

    <section class="mb-4">
        <h4>Données personnelles</h4>
        <p>
            Conformément à la réglementation en vigueur, certaines données personnelles peuvent être collectées.  
            Vous pouvez demander leur suppression ou modification à tout moment.
        </p>
    </section>

    <section class="mb-4">
        <h4>Cookies</h4>
        <p>
            Ce site utilise des cookies afin d’améliorer l’expérience utilisateur.
        </p>
    </section>

    <section class="mb-4">
        <h4>Liens externes</h4>
        <p>
            Le site peut contenir des liens vers des sites externes.  
            EcoRide n’est pas responsable de leur contenu.
        </p>
    </section>

    <section class="mb-4">
        <h4>Droit applicable</h4>
        <p>
            Les présentes mentions légales sont régies par le droit français.
        </p>
    </section>

</main>
{% endblock %}

templates/pages/mesCovoiturages.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ecoride{% endblock %}

{% block body %}
<body>
    <main>
            <h2>Historique de vos covoiturages</h2>
            <div>
                <p>Voici la liste de tous les covoiturages que vous avez proposés jusqu'à présent.</p>
            </div>
    </main>
</body>
{% endblock %}

templates/pages/mesReservations.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ecoride{% endblock %}

{% block body %}
<body>
    <main>
        <h2>Historique de vos réservations</h2>
        <div>
            <p>Voici la liste de toutes les réservations que vous avez effectuées jusqu'à présent.</p>
        </div>
        {% if reservations|length %}
            {% for reservation in reservations %}
                        <li>
                            <div class="card">
            <div class="card-header">
                Featured
            </div>
            <div class="card-body">
                <h5 class="card-title"><strong>Covoiturage ID :</strong> {{ reservation.covoiturageId }}</h5>
                <p class="card-text"><strong>Date de réservation :</strong> {{ reservation.date | date('d/m/Y H:i') }}</p>
                <p class="card-text"><strong>Statut :</strong> {{ reservation.statut }}</p>
            </div>
            </div>
                </li>
            {% endfor %}
        {% else %}
            <p>Vous n'avez effectué aucune réservation pour le moment.</p>
        {% endif %}
        </main>
</body>
{% endblock %}

templates/pages/saisirCovoiturage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ecoride{% endblock %}

{% block body %}
<main>

    <h2 class="saisir-title">Saisir un nouveau voyage</h2>

        <div class="form-container">
            {{ form_start(form) }}
                {{ form(form) }}
            {{ form_end(form) }}
        </div>
</main>
{% endblock %} 

templates/pages/user.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<main>

    <h2 class="user-title">Bienvenue sur votre espace utilisateur</h2>

    <div class="text-user">
        <p>Gérez vos informations personnelles, vos trajets et vos réservations ici.</p>
    </div>

    <div class="profil-actions">
        <a class="btn-eco" href="{{ path('app_saisir_covoiturage') }}">
            Proposer un covoiturage
        </a>

        <a class="btn-eco" href="{{ path('app_mes_covoiturages') }}">
            Voir mes covoiturages
        </a>

        <a class="btn-eco" href="{{ path('app_reservations') }}">
            Voir mes réservations
        </a>

        <a class="btn-eco" href="{{ path('app_logout') }}">
            Se déconnecter
        </a>
    </div>

    <div class="text-user">
        <p><strong>Type d’utilisateur :</strong> {{ app.user.typeUtilisateur }}</p>
    </div>

</main>
{% endblock %}